version: 0.0
os: linux

hooks:
  AfterInstall:
    - location: Scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: Scripts/stop_container.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Scripts/start_container.sh
      timeout: 300
      runas: root